### ISSUE TITLE
Exceed varchar(256) error: Collect Statistics in KAP 2.3 integrated into Azure HDInsight

### ISSUE THREAD

**Issue by codedjw** [Kyligence/KAP-manual#187]
Hi,

I am using KAP 2.3 which is integrated into Azure HDInsight.

When I import the HIVE table and start "Collect Statistics" jobs, the job is failed. And the MR log shows that:

2017-08-09 05:37:34,378 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1502246742699_0038_m_000000_0: Error: java.lang.IllegalArgumentException: '**********' exceeds the expected length for type varchar(256)
	at org.apache.kylin.metadata.datatype.StringSerializer.serialize(SourceFile:43)
	at org.apache.kylin.metadata.datatype.StringSerializer.serialize(SourceFile:25)
	at io.kyligence.kap.source.hive.tablestats.HiveTableExtSampler.code(SourceFile:244)
	at io.kyligence.cv.doCleanup(SourceFile:108)
	at org.apache.kylin.engine.mr.KylinMapper.cleanup(SourceFile:71)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:149)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:170)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1865)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:164)

**Note: '*********' is a string with 588 characters.**

**But in my imported hive table, this field is set to varchar(1000) and in hive shell, I see that KAP generate a table called 'kylin_intermediate_default_XXXX' and its schema is the same as the imported hive table (with this field varchar(1000)), and in this intermediate table, I find the selected 10000 rows have been already included.**

---------------------------------

**I want to know how to fix it ???**

Thanks

**Comment by shaofengshi** [comment]
Hi Jiawei,

This repository is to manage the KAP manual; For KAP/Kylin issues, we use kybot to follow up. Could you please register an account in https://kybot.io/ ? and then you can search the knowledge base, or as a question. Thanks.

**Comment by codedjw** [comment]
Thanks, I will turn to kybot.io for help.
